### ISSUE TITLE
CICD updates post organization move

### ISSUE THREAD

**Issue by ncgl-syngenta** [syngenta/acai-python#47]
Taking some time to lay out what steps we need for syngenta to continue using this package.

1. Acquire pypi credentials for building and uploading package to pypi
2. Update module paths for new name (is this name not taken in pypi?)
3. Update CICD (likely to github actions, but your call) to upload to pypi

**Comment by paulcruse3** [comment]
@ncgl-syngenta I am working on this part now. CICD is still through circleci and is the build is working now. 

I need to add documentation on how to contribute since I've changed the development flow to be more inclusive of alternative computer stations. 

Will update the readme as soon as I can. but everything will be in the `2.0` branch
